spring:
  profiles:
    include:
    - oauth
  application:
    name: club
  datasource:
    url: jdbc:log4jdbc:mariadb://np.sangwon97.com:3306/security
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sample
    password: 1234
  security:
    user:
      name: user1
      password: $2a$10$YP7wdCG6hYvKZD9DjVAJUOSwVkJUxuOgnqXko5mAwBha3/us7PKqm
      roles:
      - USER

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: html
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/resources
      - templates
server:
  servlet:
    encoding:
      force: true
    # context-path: /guestbook